# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon ivypiano
open_collective: # Replace with a single Open Collective ivypiano
ko_fi: # Replace with a single Ko-fi ivypiano
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay ivypiano
issuehunt: # Replace with a single IssueHunt ivypiano
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar ivypiano
buy_me_a_coffee: # Replace with a single Buy Me a Coffee ivypiano
thanks_dev: # Replace with a single thanks.dev ivypiano
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
